apiVersion: v1
kind: Service
metadata:
  name: employee-api-service
spec:
  type: NodePort
  ports:
    - port: 8002
      targetPort: 8002
      nodePort: 30009
      name: emp-api
  selector:
    app: employee-api