apiVersion: v1
kind: Pod
metadata:
  name: employee-db-pod
  labels:
    app: employee-db
spec:
  containers:
    - name: db
      image: company_sql_server:latest
      imagePullPolicy: IfNotPresent
      env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_PID
          value: "Express"
        - name: SA_PASSWORD
          value: "Banana100"
        - name: MSSQL_USER
          value: "demouser"
        - name: MSSQL_PASSWORD
          value: "Demo123!"
        - name: MSSQL_DB
          value: "Company"      