apiVersion: v1
kind: Pod
metadata:
  name: employee-api-pod
  labels:
    app: employee-api
spec:
  containers:
    - name: employee-api
      image: dileepbhatmalpe/employee-web-api:1.0
      imagePullPolicy: IfNotPresent
      env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_HTTP_PORTS
          value: "8002"      